package bizz.enumeration;

public enum MobilityState {
    PENDING,
    CREATED,
    IN_PREPARATION,
    PAYMENT_CLEARANCE,
    PAYMENT_REQUESTED,
    SECOND_PAYMENT_CLEARANCE,
    SECOND_PAYMENT_REQUESTED
}
